spring:
  mvc:
    favicon:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/dbinkus?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true