spring:
  mvc:
    favicon:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/dbinkus?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: inql.apbzd.shop.LocalMysqlDialect
    database: mysql
    show-sql: true