spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbinkus?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true